SELECT
    B.BOOK_ID,
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM
    BOOK AS B
WHERE
    B.CATEGORY = '인문'
AND
    B.PUBLISHED_DATE BETWEEN '2021-01-01' AND '2021-12-31'
ORDER BY 
    B.PUBLISHED_DATE;
    